requires "perl", "5.10.0";
requires "Digest::SHA";
requires "Mojolicious";
requires "Authen::Simple";
requires "Authen::Simple::Passwd";
requires "Authen::Simple::ActiveDirectory";
requires "Authen::Simple::CDBI";
requires "Authen::Simple::DBI";
requires "Authen::Simple::FTP";
requires "Authen::Simple::HTTP";
requires "Authen::Simple::Kerberos";
requires "Authen::Simple::LDAP";
requires "Authen::Simple::NIS";
requires "Authen::Simple::PAM";
requires "Authen::Simple::POP3";
requires "Authen::Simple::RADIUS";
requires "Authen::Simple::SMTP";
requires "Authen::Simple::SSH";

#feature "smb", "authen for smb" => sub {
#    requires "Authen::Smb";
#    requires "Authen::Simple::SMB";
#};

