#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

# Allow messages of indefinite size
$ENV{MOJO_MAX_MESSAGE_SIZE} = 0;

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('KbnAuth');
